# Microservices 1 deployment in Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: pavel12829/app1:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR
              value: "value"
