# Microservices 2 deployment in Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas:
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: pavel12829/app2:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR
              value: "value"
